config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  post 'contacts/create'
  get 'teamdetails/new'
  post 'teamdetails' => 'teamdetails#create'
  resources :posts
  root 'home#home'
  get 'home' => 'home#home'
  get 'home/terms' => 'home#terms'
  get 'home/privacy' => 'home#privacy'
  get 'home/caution' => 'home#caution'
  get 'home/timeout' => 'home#timeout'

  get 'admins' => 'admins#index'
  get 'admins/seek' => 'admins#seek'
  get 'admins/people' => 'admins#people'
  get 'admins/users/:id/person' => 'admins#person', as: 'person'
  get 'admins/users/:id/person_edit' => 'admins#person_edit', as: 'person_edit'
  patch 'admins/users/:id' => 'admins#update'
  put 'admins/users/:id' => 'admins#update'
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
 }
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
 }

  get 'application/session_time'
  devise_scope :user do
    match 'active' => 'users/sessions#active', via: :get
    match 'timeout' => 'users/sessions#timeout', via: :get
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :users, except: [:create] do
   collection do
    get 'search'
   end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, length: {maximum:255}
  validates :message, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: {maximum: 50}
  validates :body, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/team_detail.rb
class TeamDetail < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :validatable,:authentication_keys => [:tell]

  attachment :image
  has_one :team_detail, dependent: :destroy
  accepts_nested_attributes_for :team_detail ,allow_destroy: true
  has_many :posts, dependent: :destroy
   # usernameを必須・一意とする
   validates_uniqueness_of :name, :team_name, :captain_name, :tell
   validates_presence_of :name, :team_name, :captain_name, :tell
   # DM機能
   has_many :messages, dependent: :destroy
   has_many :entries, dependent: :destroy

   # paranoia
   acts_as_paranoid

   # 半角数字0~9を10回繰り返しor11回繰り返しで一致
   VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
   validates :tell, presence: true, format: { with: VALID_PHONE_REGEX }

  # No use email
 def email_required?
   false
 end

 def email_changed?
  false
 end

 def will_save_change_to_email?
   false
 end

 #検索機能
 def self.search(search)
   return User.all unless search
   User.where(['content LIKE ?', "%#{search}%"])
 end

 def self.search(seek)
    return User.all unless seek
    User.where(['name LIKE ?', "%#{seek}%"])
 end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :new_message_badge, if: :user_signed_in?

  def home
    if User.last(3).nil?
    else
     @newuser = User.last(3)
   end
  end

    def caution
    end

    def privacy
    end

    def terms
    end

    def timeout
    end
 end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate!, only: [:new, :show, :edit, :update]
  before_action :new_message_badge, if: :user_signed_in?

  def index
     @teamdetails = TeamDetail.all
     @posts = Post.all.reverse_order
     @plan = Post.where(conditions: "予定を合わせて対戦").reverse_order
     @now = Post.where(conditions: "いますぐ試合したい").reverse_order
     @pleasant = Post.where(conditions: "わいわい試合したい").reverse_order
     @serious = Post.where(conditions: "真剣勝負!").reverse_order
     render :index, layout: false
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if admin_signed_in?
      flash[:posterror] = 'ログインユーザーのみ投稿できます'
      render :new
    else
      @post.user_id = current_user.id
    if  @post.save
      redirect_to posts_path
    else
      render action: :new
    end
   end
  end

  def show
    if admin_signed_in?
      @post = Post.find(params[:id])
      @user = @post.user
      @team = TeamDetail.find_by(user_id: @user.id)
    else
    @post = Post.find(params[:id])
    @user = @post.user
    @team = TeamDetail.find_by(user_id: @user.id)
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
     unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
       end
       if @isRoom
       else
         @room = Room.new
         @entry = Entry.new
       end
     end
   end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:destroypostmessage] = '削除しました'
      redirect_to posts_path
    else
      render :show
  end
end

  private
  def post_params
    params.require(:post).permit(:title, :body, :conditions)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def new_message_badge
    @currentEntries = current_user.entries
    myRoomIds = []

    @currentEntries.each do |entry|
     myRoomIds << entry.room.id
    end
    @anotherEntries = Entry.where(room_id: myRoomIds).where( 'user_id != ?', current_user.id)
    # 総未読数取得
    unreads = []
    @room_messages = Message.where(room_id: myRoomIds)
    @room_messages.each do |message|
      if message.read_flg == 1 && message.user_id != current_user.id
         unreads << message.read_flg
       end
      end
     @unreads = 0
     @unreads += unreads.sum
     content_tag(:span, @unreads, class: 'unread-num')
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    messages = resource.errors.full_messages.each do |errmsg|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{errmsg}
      </div>
      EOF
    end
    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/teamdetails_helper.rb
module TeamdetailsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/index.html.erb
  <h1 class="center margin1">管理者用ホーム</h1>
   <div class="frame">
    <div class="center margin1"><%= link_to 'ユーザー情報をみる', admins_people_path %></div>
    <div class="center margin1"><%= link_to '掲示板を見る', posts_path %></div>
   </div>

app/views/admins/people.html.erb
   <div class="center margin1">
    <%= form_tag(admins_seek_path, :method => 'get') do %>
     <%= text_field_tag :seek %>
      <%= submit_tag '検索', :name => nil %>
     <% end %>
    </div>
     <div class="center">
      <h1 class="center margin1">ユーザー一覧</h1>
     </div>
      <div class="container">
       <div class="row justify-content-center">
        <div class="col-sm-8 col-sm-offset-2 col-lg-8 col-lg-offset-2">
         <table class="table">
          <thead>
           <tr>
            <th>アイコン</th>
            <th>名前</th>
            <th>電話番号</th>
           </tr>
          </thead>
         <tbody>
          <% @users.each do |user| %>
           <tr>
            <td><%= attachment_image_tag user, :image, :fill, 63, 63, fallback: "no_image2.png" %></td>
            <td><%= link_to user.name, person_path(user) %></td>
            <td><%= user.tell %></td>
           </tr>
          <% end %>
         </tbody>
        </table>
       </div>
       </div>
      </div>

app/views/admins/person.html.erb
  <h1 class="center margin1">ユーザー詳細</h1>
   <div class="container">
    <div class="row">
     <div class="col-lg-4 col-md-6 col-sm-6 center">
      <div class="margin1 smartphone"><%= attachment_image_tag @user, :image, :fill, 300, 300, fallback: "no_image.png" %></div>
      <div class="margin2"><%= link_to "編集", person_edit_path, class: 'btn btn-success various-width' %></div>
      <div class="margin2"><%= link_to "強制退会", user_path, method: :delete, data: { confirm: '本当に退会させますか？データは残りますので復元することも可能です。' }, class: "pull-danger", class: "btn btn-danger btn-xs various-width" %></div>
      <div class="margin2"><%= link_to 'ユーザー一覧へ戻る', admins_people_path, class: 'btn btn-primary various-width' %></div>
     </div>
      <div class="col-lg-8 col-md-6 col-sm-6 ">
       <div class="font3">電話番号</div>
        <div class="font1 show-border"><%= @user.tell %></div>
       <div class="font3">名前</div>
        <div class="font1 show-border"><%= @user.name %></div>
       <div class="font3">キャプテン</div>
        <div class="font1 show-border"><%= @user.captain_name %></div>
       <div class="font3">チーム名</div>
        <div class="font1 show-border"><%= @user.team_name %></div>
       <% if @user.team_detail.present? %>
        <div class="font3">男性人数</div>
         <div class="font1 show-border"><%= @team.male %></div>
        <div class="font3">女性人数</div>
         <div class="font1 show-border"><%= @team.female %></div>
        <div class="font3">経験者人数</div>
         <div class="font1 show-border"><%= @team.experience %></div>
        <div class="font3">初心者人数</div>
         <div class="font1 show-border"><%= @team.beginner %></div>
        <div class="font3">紹介文</div>
         <div class="font1 show-border"><%= @team.introduction %></div>
        <div class="font3">チームレベル</div>
         <div class="font1 show-border"><%= @team.team_level %></div>
        <div class="font3">活動地域</div>
         <div class="font1 show-border"><%= @team.active_area %></div>
        <div class="font3">活動時間</div>
         <div class="font1 show-border"><%= @team.active_time %></div>
        <% end %>
       </div>
      </div>
     </div>

app/views/admins/person_edit.html.erb
<h1 class="center margin1">ユーザー編集</h1>
 <div class="margin1">
  <div class="container">
   <div class="row justify-content-center">
    <div class="col-md-8 col-sm-8">
     <%= form_for @user, :url => { :controller => :admins, :action => :update } do |f| %>
       <%= render 'layouts/error_messages', model: f.object %>
      <h4 class="font4">名前</h4>
       <div class="form-group">
        <%= f.text_field :name, class: 'form-control mw-100' %>
       </div>
      <h4 class="font4">キャプテン</h4>
       <div class="form-group">
        <%= f.text_field :captain_name, class: 'form-control mw-100' %>
       </div>
      <h4 class="font4">チーム名</h4>
       <div class="form-group">
        <%= f.text_field :team_name, class: 'form-control mw-100' %>
       </div>
      <h4 class="font4">電話番号</h4>
       <div class="form-group">
        <%= f.text_field :tell, class: 'form-control mw-100' %>
       </div>
      <h4 class="font4">画像</h4>
       <div class="form-group">
        <%= f.attachment_field :image %>
       </div>
        <%= f.fields_for :team_detail do |team| %>
         <h4 class="font4">経験者人数</h4>
          <div class="form-group">
          <%= team.number_field :experience, class: 'form-control mw-100' %>
         </div>
        <h4 class="font4">初心者人数</h4>
         <div class="form-group">
          <%= team.number_field :beginner, class: 'form-control mw-100' %>
         </div>
        <h4 class="font4">男性人数</h4>
         <div class="form-group">
          <%= team.number_field :male, class: 'form-control mw-100' %>
         </div>
        <h4 class="font4">女性人数</h4>
         <div class="form-group">
          <%= team.number_field :female, class: 'form-control mw-100' %>
         </div>
        <h4 class="font4">チーム紹介文</h4>
         <div class="form-group">
         <%= team.text_area :introduction, rows: "5", placeholder: "introduction", class: 'form-control mw-100' %>
        </div>
       <h4 class="font4">チームレベル</h4>
        <div class="form-group various-select">
        <%= team.select :team_level, [["初級", "初級"], ["中級", "中級"],  ["上級", "上級"] ], :prompt => "選択してください", class: 'select-width' %>
       </div>
      <h4 class="font4">活動地域</h4>
       <div class="form-group various-select">
        <%= team.select :active_area, [["大阪", "大阪"], ["和歌山", "和歌山"],  ["奈良", "奈良"],  ["兵庫", "兵庫"],  ["京都", "京都"],  ["滋賀", "滋賀"] ], :prompt => "選択してください" %>
       </div>
      <h4 class="font4">活動時間</h4>
       <div class="form-group various-select">
        <%= team.select :active_time, [["朝", "朝"], ["昼", "昼"],  ["夕", "夕"],  ["夜", "夜"] ], :prompt => "選択してください" %>
       </div>
      <% end %>
       <%= f.submit '更新する', class: 'btn btn-info various-width' %>
      <% end %>
     </div>
    </div>
   </div>
  </div>

app/views/admins/seek.html.erb
  <h1 class="center margin1">ユーザー検索結果</h1>
  <div class="container">
   <div class="row justify-content-center">
    <div class="col-sm-8 col-md-8 col-lg-8">
     <table class="table">
      <thead>
       <tr>
       <th></th>
       <th>名前</th>
       <th>電話番号</th>
      </tr>
       </thead>
        <tbody>
         <% @seek.each do |seek| %>
          <tr>
           <td><%= attachment_image_tag seek, :image, :fill, 63, 63, fallback: "no_image2.png" %></td>
           <td><%= link_to seek.name, person_path(seek) %></td>
           <td><%= seek.tell %></td>
          </tr>
         <% end %>
        </tbody>
       </table>
      </div>
     </div>
    </div>
   <div class="center margin2"><%= link_to 'ユーザー一覧へ戻る', admins_people_path %></div>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: 'margin2' %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
  <% if model.errors.any? %>
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Footsal</title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script> <!-- parallax.min.js -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
   <body>
     <!-- gem auto_session_timeout -->
     <% if user_signed_in? %>
     <div class="user_logged"></div>
     <%= auto_session_timeout_js %>
   <% end %>
    <header>
     <!-- navbar-expand-○でグローバルメニュー表示（なければハンバーガメニュー） -->
      <nav class="navbar navbar-expand-lg navbar-expand-md navbar-dark bg-primary">
       <a href="/home" id="logo" class="navbar-brand"><img src="<%= asset_path "footsal15.png" %>" alt="foosal"></a>
        <!-- <button>~</button>でハンバーガメニュー作成。data-targetで指定したIDやクラスがハンバーガメニューとなる -->
         <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
       <div class="collapse navbar-collapse" id="navbarNav">
        <% if user_signed_in? %>
         <ul class="nav navbar-nav ml-auto">
          <li class="nav-item active"><%= link_to "ホーム", root_path, class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "マイページ", user_path(current_user), class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "チーム一覧", users_path, class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "トークルーム", rooms_path, class: "nav-link" %>
           <% if user_signed_in? %>
            <% if @unreads == 0 %>
           <% else %>
           <!--Applicationhelper.rbに記載 -->
             <%= new_message_badge %>
            <% end %>
           <% end %>
          </li>
          <li class="nav-item active"><%= link_to "掲示板", posts_path, class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
         </ul>
        <% elsif admin_signed_in? %>
         <ul class="nav navbar-nav ml-auto">
          <li class="nav-item"><%= link_to "管理ホーム", admins_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ユーザー情報", admins_people_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "掲示板へ", posts_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %></li>
         </ul>
        <% else %>
         <ul class="nav navbar-nav ml-auto">
          <li class="nav-item"><%= link_to "ホーム", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "会員登録",new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ログイン", user_session_path, class: "nav-link" %></li>
         </ul>
        <% end %>
       </div>
      </nav>
     </header>
     <%= yield %>
    <footer>
     <div class="footer-navi frame contain">
      <nav class="footer-navbar">
       <ul>
        <li><span>&#155;</span><%= link_to 'ご利用にあたっての注意点', home_caution_path %></li>
        <li><span>&#155;</span><%= link_to '利用規約', home_terms_path %></li>
        <li><span>&#155;</span><%= link_to 'プライバシーポリシー', home_privacy_path %></li>
        <li><span>&#155;</span><%= link_to 'お問い合わせ', contacts_new_path %></li>
       </ul>
      </nav>
       <nav class="footer-navbar">
        <ul>
         <li><span>&#155;</span><%= link_to '募集する', new_post_path %></li>
         <li><span>&#155;</span><%= link_to '掲示板をみる', posts_path %></li>
         <li><span>&#155;</span><%= link_to '登録チーム一覧', users_path %></li>
         <li><span>&#155;</span><%= link_to 'トークルーム一覧', rooms_path %></li>
        </ul>
       </nav>
      </div>
     <div class="sticky-bottom">
      <div class="copyright">
       <p>&copy; 2019 foosal</p>
      </div>
     </div>
    </footer>
   </body>
  </html>