config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  post 'contacts/create'
  get 'teamdetails/new'
  post 'teamdetails' => 'teamdetails#create'
  resources :posts
  root 'home#home'
  get 'home' => 'home#home'
  get 'home/terms' => 'home#terms'
  get 'home/privacy' => 'home#privacy'
  get 'home/caution' => 'home#caution'
  get 'home/timeout' => 'home#timeout'

  get 'admins' => 'admins#index'
  get 'admins/seek' => 'admins#seek'
  get 'admins/people' => 'admins#people'
  get 'admins/users/:id/person' => 'admins#person', as: 'person'
  get 'admins/users/:id/person_edit' => 'admins#person_edit', as: 'person_edit'
  patch 'admins/users/:id' => 'admins#update'
  put 'admins/users/:id' => 'admins#update'
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
 }
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
 }

  get 'application/session_time'
  devise_scope :user do
    match 'active' => 'users/sessions#active', via: :get
    match 'timeout' => 'users/sessions#timeout', via: :get
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :users, except: [:create] do
   collection do
    get 'search'
   end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :validatable,:authentication_keys => [:tell]

  attachment :image
  has_one :team_detail, dependent: :destroy
  accepts_nested_attributes_for :team_detail ,allow_destroy: true
  has_many :posts, dependent: :destroy
   # usernameを必須・一意とする
   validates_uniqueness_of :name, :team_name, :captain_name, :tell
   validates_presence_of :name, :team_name, :captain_name, :tell
   # DM機能
   has_many :messages, dependent: :destroy
   has_many :entries, dependent: :destroy

   # paranoia
   acts_as_paranoid

   # 半角数字0~9を10回繰り返しor11回繰り返しで一致
   VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
   validates :tell, presence: true, format: { with: VALID_PHONE_REGEX }

  # No use email
 def email_required?
   false
 end

 def email_changed?
  false
 end

 def will_save_change_to_email?
   false
 end

 #検索機能
 def self.search(search)
   return User.all unless search
   User.where(['content LIKE ?', "%#{search}%"])
 end

 def self.search(seek)
    return User.all unless seek
    User.where(['name LIKE ?', "%#{seek}%"])
 end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :new_message_badge, if: :user_signed_in?
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
    # super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    #サインアップ時
    teamdetails_new_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
    # super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # gem auto_session_timeout
  def active
    render_session_status
  end

  def timeout
    # render_session_timeout
    redirect_to home_timeout_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate!, only: [:show, :edit, :update]
  before_action :new_message_badge, if: :user_signed_in?

  def search
    # 検索する値が「""」と等しい場合はfalseで処理は実行されない（検索を選択していないとblankが返ってくる）
    # 値が「""」以外であればtrueとなる（処理実行）。
    @search = TeamDetail.all
    if params[:team_level] != ""
      @search = @search.where(team_level: params[:team_level])
    end
    if params[:active_area] != ""
      @search = @search.where(active_area: params[:active_area])
    end
    if params[:active_time] != ""
      @search = @search.where(active_time: params[:active_time])
    end
    if params[:male] != ""
      @search = @search.where(male: params[:male])
    end
    if params[:female] != ""
      @search = @search.where(female: params[:female])
    end
    if params[:experience] != ""
      @search = @search.where(experience: params[:experience])
    end
    if params[:beginner] != ""
      @search = @search.where(beginner: params[:beginner])
    end
  end

  def seek
    @seek = User.find(params[:seek])
  end

  def index
     @users = User.page(params[:page]).per(8).reverse_order
  end

  def show
     @user = User.find(params[:id])
     @team = TeamDetail.find_by(user_id: @user.id)
     @currentUserEntry = Entry.where(user_id: current_user.id)
     @userEntry = Entry.where(user_id: @user.id)
      unless @user.id == current_user.id
       @currentUserEntry.each do |cu|
         @userEntry.each do |u|
           if cu.room_id == u.room_id then
             @isRoom = true
             @roomId = cu.room_id
           end
         end
        end
        if @isRoom
        else
          @room = Room.new
          @entry = Entry.new
        end
      end
   end

  def edit
     @user = User.find(params[:id])
      if @user == current_user
     else
      redirect_to users_path
     end
  end

  def update
  @user = User.find(params[:id])
  require "refile/mini_magick"

  if @user.update(user_params)
     # @user.update(params.require(:user).permit(:name, :captain_name, :team_name, :tell))
      redirect_to user_path(@user.id)
     else
      flash.now[:alert] = "正しく記入してください。"
      render :edit
    end
  end

  def destroy
     User.find(params[:id]).destroy
    if user_signed_in?
      flash[:unsubscribe] = "ご利用ありがとうございました！"
     redirect_to home_path
    else
     redirect_to home_path
    end
  end

   private
  def user_params
    params.require(:user).permit(:name, :captain_name, :team_name, :tell, :image,
    team_detail_attributes:[:id, :experience, :beginner, :male, :female, :introduction, :team_level, :active_area, :active_time])
  end
 end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
  <h1 class="center margin1">ユーザー編集</h1>
   <div class="margin1">
    <div class="container">
     <div class="row justify-content-center ">
      <div class="col-md-8 col-sm-8"> 
       <%= form_for(@user) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
         <h4 class="font4">名前</h4>
          <div class="form-group">
          <%= f.text_field :name, class: 'form-control mw-100' %>
         </div>
        <h4 class="font4">キャプテン</h4>
         <div class="form-group">
          <%= f.text_field :captain_name, class: 'form-control mw-100' %>
         </div>
        <h4 class="font4">チーム名</h4>
         <div class="form-group">
          <%= f.text_field :team_name, class: 'form-control mw-100' %>
         </div>
        <h4 class="font4">電話番号</h4>
         <div class="form-group">
          <%= f.text_field :tell, class: 'form-control mw-100' %>
         </div>
        <h4 class="font4">画像</h4>
         <div class="form-group">
          <%= f.attachment_field :image %>
         </div>
          <%= f.fields_for :team_detail do |team| %>
           <h4 class="font4">経験者人数</h4>
            <div class="form-group">
            <%= team.number_field :experience, class: 'form-control mw-100' %>
           </div>
          <h4 class="font4">初心者人数</h4>
           <div class="form-group">
            <%= team.number_field :beginner, class: 'form-control mw-100' %>
           </div>
          <h4 class="font4">男性人数</h4>
           <div class="form-group">
            <%= team.number_field :male, class: 'form-control mw-100' %>
           </div>
          <h4 class="font4">女性人数</h4>
           <div class="form-group">
            <%= team.number_field :female, class: 'form-control mw-100' %>
           </div>
          <h4 class="font4">チーム紹介文</h4>
           <div class="form-group">
           <%= team.text_area :introduction, rows: "5", placeholder: "introduction", class: 'form-control mw-100' %>
          </div>
         <h4 class="font4">チームレベル</h4>
          <div class="form-group various-select">
          <%= team.select :team_level, [["初級", "初級"], ["中級", "中級"],  ["上級", "上級"] ], :prompt => "選択してください", class: 'select-width' %>
         </div>
        <h4 class="font4">活動地域</h4>
         <div class="form-group various-select">
          <%= team.select :active_area, [["大阪", "大阪"], ["和歌山", "和歌山"],  ["奈良", "奈良"],  ["兵庫", "兵庫"],  ["京都", "京都"],  ["滋賀", "滋賀"] ], :prompt => "選択してください" %>
         </div>
        <h4 class="font4">活動時間</h4>
         <div class="form-group various-select">
          <%= team.select :active_time, [["朝", "朝"], ["昼", "昼"],  ["夕", "夕"],  ["夜", "夜"] ], :prompt => "選択してください" %>
         </div>
        <% end %>
         <%= f.submit '更新する', class: 'btn btn-info various-width' %>
        <% end %>
       </div>
      </div>
     </div>
    </div>

app/views/users/index.html.erb
     <section>
      <div class="main1">
          <h1 class="center margin1">チーム情報</h1>

        <div class="contain">
         <% @users.each do |user| %>
          <div class="flex double-frame-use">
           <div class="item1 phone-size"><%= attachment_image_tag user, :image, :fill, 300, 300, fallback: "no_image.png" %></div>
            <div class="item2 center font1"><%= user.team_name %></div>
           <% if user_signed_in? %>
            <div class="center"><%= link_to '詳細', user_path(user) %></div>
           <% elsif admin_signed_in? %>
            <div class="center"><%= link_to '管理者画面で詳細へ', person_path(user) %></div>
           <% else %>
            <div class="center"><%= link_to '詳細', user_session_path %></div>
           <% end %>
          </div>
         <% end %>
        </div>
       </div>
      </section>
     <div class="margin1"><%= paginate(@users) %></div>

     <div class="frame">
       <div class="container">
        <div class="row justify-content-center">
         <div class="col-md-8 double-frame-use">
          <%= form_tag(search_users_path, :method => 'get') do %>
           <h4 class="font4  marginbottom1">チームレベル</h4>
            <div class="various-select marginbottom2">
             <%= select_tag(:team_level, options_for_select([["初級", "初級" ], ["中級", "中級" ], ["上級", "上級" ]]), :include_blank => "選択してください") %>
            </div>
             <h4 class="font4 marginbottom1">活動地域</h4>
              <div class="various-select marginbottom2">
               <%= select_tag(:active_area, options_for_select([["大阪", "大阪" ], ["和歌山", "和歌山" ], ["奈良", "奈良" ], ["兵庫", "兵庫" ], ["京都", "京都" ], ["滋賀", "滋賀" ]]), :include_blank => "選択してください") %>
              </div>
             <h4 class="font4  marginbottom1">活動時間</h4>
              <div class="various-select marginbottom2">
              <%= select_tag(:active_time, options_for_select([["朝", "朝" ], ["昼", "昼" ], ["夕", "夕" ], ["夜", "夜" ]]), :include_blank => "選択してください") %>
             </div>
            <h4 class="font4  marginbottom1">男性人数</h4>
             <div class="various-select marginbottom2">
              <%= select_tag(:male, options_for_select((0..50).to_a ), :include_blank => "選択してください") %>
             </div>
            <h4 class="font4  marginbottom1">女性人数</h4>
             <div class="various-select marginbottom2">
              <%= select_tag(:female, options_for_select((0..50).to_a ), :include_blank => "選択してください") %>
             </div>
            <h4 class="font4  marginbottom1">経験者</h4>
             <div class="various-select marginbottom2">
              <%= select_tag(:experience, options_for_select((0..50).to_a ), :include_blank => "選択してください") %>
             </div>
            <h4 class="font4  marginbottom1">初心者</h4>
             <div class="various-select marginbottom2">
              <%= select_tag(:beginner, options_for_select((0..50).to_a ), :include_blank => "選択してください") %>
             </div>
              <%= submit_tag '検索', class: 'btn btn-info margin1 various-width' %>
             <% end %>
            </div>
           </div>
          </div>
         </div>

app/views/users/search.html.erb
   <section>
    <div class="main1">
     <h2 class="center margin1">チーム情報</h2>
      <div class="contain">
       <% @search.each do |search| %>
        <div class="flex double-frame-use">
         <div class="item1 phone-size"><%= attachment_image_tag search.user, :image, :fill, 300, 300, fallback: "no_image.png" %></div>
         <div class="item2 center font1"><%= search.user.team_name %></div>
         <% if user_signed_in? %>
         <div class="center"><%= link_to '詳細', user_path(search.user) %></div>
         <% elsif admin_signed_in? %>
         <div class="center"><%= link_to '管理者画面で詳細へ', person_path(search.user) %></div>
         <% else %>
         <div class="center"><%= link_to '詳細', user_session_path %></div>
        <% end %>
        </div>
       <% end %>
      </div>
     </div>
    </section>
    <div class="center"><%= link_to '検索に戻る', users_path %></div>

app/views/users/show.html.erb
   <% if @user.id == current_user.id %>
    <h1 class="center margin1">マイページ</h1>
     <div class="container">
      <div class="row">
       <div class="col-lg-4 col-md-6 col-sm-6 center">
        <div class="margin1 smartphone"><%= attachment_image_tag @user, :image, :fill, 300, 300, fallback: "no_image.png", auto_orient: true %></div>
         <div class="margin2"><%= link_to '編集する', edit_user_path, class: 'btn btn-success button-width' %></div>
         <div class="margin2"><%= link_to 'pass変更', edit_user_registration_path, class: 'btn btn-primary button-width' %></div>
         <div class="margin2"><%= link_to "退会", user_path, method: :delete, data: { confirm: '退会します。本当によろしいですか?' }, class: "btn btn-danger button-width" %></div>
        </div>
         <div class="col-lg-8 col-md-6 col-sm-6 ">
          <div class="font3">名前</div>
           <div class="font1 show-border"><%= @user.name %></div>
          <div class="font3">キャプテン</div>
           <div class="font1 show-border"><%= @user.captain_name %></div>
          <div class="font3">チーム名</div>
           <div class="font1 show-border"><%= @user.team_name %></div>
            <% if @user.team_detail.present? %>
             <div class="font3">男性人数</div>
              <div class="font1 show-border"><%= @team.male %></div>
             <div class="font3">女性人数</div>
              <div class="font1 show-border"><%= @team.female %></div>
             <div class="font3">経験者人数</div>
              <div class="font1 show-border"><%= @team.experience %></div>
             <div class="font3">初心者人数</div>
              <div class="font1 show-border"><%= @team.beginner %></div>
             <div class="font3">紹介文</div>
              <div class="font1 show-border"><%= @team.introduction %></div>
             <div class="font3">チームレベル</div>
              <div class="font1 show-border"><%= @team.team_level %></div>
             <div class="font3">活動地域</div>
              <div class="font1 show-border"><%= @team.active_area %></div>
             <div class="font3">活動時間</div>
              <div class="font1 show-border"><%= @team.active_time %></div>
             <% end %>
            </div>
           </div>
          </div>
         <% else %>
          <h1 class="center margin1">ユーザー情報</h1>
           <div class="container">
            <div class="row">
             <div class="col-lg-4 col-md-6 col-sm-6 center">
              <div class="margin1 smartphone"><%= attachment_image_tag @user, :image, :fill, 300, 300, fallback: "no_image.png" %></div>
               <% if @isRoom == true %>
                <!--すでにroomがあるならそのroomへ、そうでなければroomを新たにcreate-->
                <div class="margin2 font1"><p><a href="/rooms/<%= @roomId %>">トークルームへ</a></p></div>
               <% else %>
                <%= form_for(@room) do |f| %>
                 <%= fields_for @entry do |e| %>
                  <% e.hidden_field :user_id, value: @user.id %>
                 <% end %>
                 <div class="margin2"><%= f.submit "トークを始める", class: 'btn btn-info' %></div>
                <% end %>
               <% end %>
              </div>
               <div class="col-lg-8 col-md-6 col-sm-6 ">
                <div class="font3">キャプテン</div>
                 <div class="font1 show-border"><%= @user.captain_name %></div>
                <div class="font3">チーム名</div>
                 <div class="font1 show-border"><%= @user.team_name %></div>
                  <% if @user.team_detail.present? %>
                   <div class="font3">男性人数</div>
                    <div class="font1 show-border"><%= @team.male %></div>
                   <div class="font3">女性人数</div>
                    <div class="font1 show-border"><%= @team.female %></div>
                   <div class="font3">経験者人数</div>
                    <div class="font1 show-border"><%= @team.experience %></div>
                   <div class="font3">初心者人数</div>
                    <div class="font1 show-border"><%= @team.beginner %></div>
                   <div class="font3">紹介文</div>
                    <div class="font1 show-border"><%= @team.introduction %></div>
                   <div class="font3">チームレベル</div>
                    <div class="font1 show-border"><%= @team.team_level %></div>
                   <div class="font3">活動地域</div>
                    <div class="font1 show-border"><%= @team.active_area %></div>
                   <div class="font3">活動時間</div>
                    <div class="font1 show-border"><%= @team.active_time %></div>
                   <% end %>
                  </div>
                 </div>
                </div>
               <% end %>

app/views/users/talks.html.erb
  <% if @user.id == current_user.id %>
   <% else %>
    <% if @isRoom == true %>
     <p><a href="/rooms/<%= @roomID %>">チャットへ</a></p>
    <% else %>
     <%= form_for(@room) do |f| %>
      <%= f.fields_for @entry do |e| %>
       <%= e.hidden_field :user_id, :value => @user.id %>
      <% end %>
       <%= f.submit 'チャットを始める' %>
      <% end %>
     <% end %>
    <% end %>
     <% link_to 'ユーザー一覧に戻る', users_path %>

app/views/users/test.html.erb
  <% if @user.id == current_user.id %>
   <% else %>
    <% if @isRoom == true %>
     <p><a href="/rooms/<%= @roomID %>">チャットへ</a></p>
    <% else %>
     <%= form_for(@room) do |f| %>
      <%= f.fields_for @entry do |e| %>
       <%= e.hidden_field :user_id, :value => @user.id %>
      <% end %>
       <%= f.submit 'チャットを始める' %>
      <% end %>
     <% end %>
    <% end %>
     <% link_to 'ユーザー一覧に戻る', users_path %>

これはログイン画面でのパスワード忘れた時の
    <%= render "users/shared/links" %>


    def create
      @room = Room.create
      @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
      @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
      redirect_to "/rooms/#{@room.id}"
    end


    @currentEntries = current_user.entries
    myRoomIds = []

    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end
    @anotherEntries = Entry.where(room_id: myRoomIds).where( 'user_id != ?', current_user.id)

    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))

    @anotherEntries.each do |ae|
      binding.pry
       if ae.user_id == @entry2.user_id
         p "test"
         render template: "home/home" and return
         @room.destroy
         @entry1.destroy
         @entry2.destroy
         binding.pry
       else
         redirect_to "/rooms/#{@room.id}" and return
     end
    end
    end