config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  post 'contacts/create'
  get 'teamdetails/new'
  post 'teamdetails' => 'teamdetails#create'
  resources :posts
  root 'home#home'
  get 'home' => 'home#home'
  get 'home/terms' => 'home#terms'
  get 'home/privacy' => 'home#privacy'
  get 'home/caution' => 'home#caution'
  get 'home/timeout' => 'home#timeout'

  get 'admins' => 'admins#index'
  get 'admins/seek' => 'admins#seek'
  get 'admins/people' => 'admins#people'
  get 'admins/users/:id/person' => 'admins#person', as: 'person'
  get 'admins/users/:id/person_edit' => 'admins#person_edit', as: 'person_edit'
  patch 'admins/users/:id' => 'admins#update'
  put 'admins/users/:id' => 'admins#update'
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
 }
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
 }

  get 'application/session_time'
  devise_scope :user do
    match 'active' => 'users/sessions#active', via: :get
    match 'timeout' => 'users/sessions#timeout', via: :get
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :users, except: [:create] do
   collection do
    get 'search'
   end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @currentEntries = current_user.entries
    myRoomIds = []

    @currentEntries.each do |entry|
     myRoomIds << entry.room.id
    end
    @anotherEntries = Entry.where(room_id: myRoomIds).where( 'user_id != ?', current_user.id)

    # 総未読数取得
    unreads = []
    @room_messages = Message.where(room_id: myRoomIds)
    @room_messages.each do |message|
      if message.read_flg == 1 && message.user_id != current_user.id
         unreads << message.read_flg
       end
      end
     @unreads = 0
     @unreads += unreads.sum
    render :index, layout: false
   end

   def create
     # @entry2.userが、もし自分が入っているroomの相手ユーザーと同じなら
     # （@entry2.user_idが@anotherEntriesに存在していたら）
     # 作成したroom,@entry1,@entry2を削除する
     @currentEntries = current_user.entries
     myRoomIds = []

     @currentEntries.each do |entry|
       myRoomIds << entry.room.id
     end
     @anotherEntries = Entry.where(room_id: myRoomIds).where( 'user_id != ?', current_user.id)

     @room = Room.create
     @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
     @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))

     if @anotherEntries.exists?(user_id: @entry2.user_id)
          @room.destroy
          @entry1.destroy
          @entry2.destroy
          redirect_to "/rooms/" and return
        else
          redirect_to "/rooms/#{@room.id}" and return
      end
     end

   def show
     @room = Room.find(params[:id])
     if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
     @messages.each do |message|
      if message.read_flg == 1 && message.user_id != current_user.id
          message.read_flg = 0
          message.save
      end
     end
      @message = Message.new
      @entries = @room.entries
      @otherentry = @entries.find_by( 'user_id != ?', current_user.id)
    else
      redirect_back(fallback_location: users_path)
   end
  render :show, layout: false
 end

end

app/views/rooms/index.html.erb
<!DOCTYPE html>
 <html lang="ja">
  <head>
   <title>Footsal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
    <body>
      <!-- gem auto_session_timeout -->
      <% if user_signed_in? %>
      <div class="user_logged"></div>
      <%= auto_session_timeout_js %>
    <% end %>
     <header>
      <!-- navbar-expand-○でグローバルメニュー表示（なければハンバーガメニュー） -->
       <nav class="navbar navbar-expand-lg navbar-expand-md navbar-dark bg-primary">
        <a href="/home" id="logo" class="navbar-brand"><img src="/images/footsal15.png" alt="foosal"></a>
         <!-- <button>~</button>でハンバーガメニュー作成。data-targetで指定したIDやクラスがハンバーガメニューとなる -->
          <button class="navbar-toggler" type="button" data-toggle="collapse"
           data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
         </button>
        <div class="collapse navbar-collapse" id="navbarNav">
         <% if user_signed_in? %>
          <ul class="nav navbar-nav ml-auto">
           <li class="nav-item active"><%= link_to "ホーム", root_path, class: "nav-link" %></li>
           <li class="nav-item active"><%= link_to "マイページ", user_path(current_user), class: "nav-link" %></li>
           <li class="nav-item active"><%= link_to "チーム一覧", users_path, class: "nav-link" %></li>
           <li class="nav-item active"><%= link_to "トークルーム", rooms_path, class: "nav-link" %>
             <% if @unreads == 0 %>
            <% else %>
            <!--Applicationhelper.rbに記載 -->
             <%= new_message_badge %>
            <% end %>
           </li>
           <li class="nav-item active"><%= link_to "掲示板", posts_path, class: "nav-link" %></li>
           <li class="nav-item active"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
          </ul>
         <% elsif admin_signed_in? %>
          <ul class="nav navbar-nav ml-auto">
           <li class="nav-item"><%= link_to "管理ホーム", admins_path, class: "nav-link" %></li>
           <li class="nav-item"><%= link_to "ユーザー情報", admins_people_path, class: "nav-link" %></li>
           <li class="nav-item"><%= link_to "掲示板へ", posts_path, class: "nav-link" %></li>
           <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %></li>
          </ul>
         <% else %>
          <ul class="nav navbar-nav ml-auto">
           <li class="nav-item"><%= link_to "ホーム", root_path, class: "nav-link" %></li>
           <li class="nav-item"><%= link_to "会員登録",new_user_registration_path, class: "nav-link" %></li>
           <li class="nav-item"><%= link_to "ログイン", user_session_path, class: "nav-link" %></li>
          </ul>
         <% end %>
        </div>
       </nav>
      </header>
       <div class="center">
        <h1 class="margin1">トーク</h1>
       </div>
        <div class="container">
         <div class="row justify-content-center">
          <div class="col-sm-8 col-md-8 col-lg-8 center row-room-index">
           <% @anotherEntries.each do |ae| %>
            <div class="block margin1">
             <%= link_to room_path(ae.room.id) do %>

              <div class="imageblock">
               <%= attachment_image_tag ae.user, :image, :fill, 63, 63, fallback: "no_image2.png", class: 'radius margin2' %>
              </div>
             <div class="talkblock">
              <p class="margin2"><%= ae.user.name %></p>
             <% end %>
              <% if ae.room.messages.present? %>
               <p class="font3"><%= ae.room.messages.last.content %></p>
                <% array = [] %>
                <!--各roomの未読数取得-->
                 <% ae.room.messages.each do |message| %>
                  <% if message.read_flg == 1 && message.user_id != current_user.id %>
                   <% total = message.read_flg %>
                    <% array << total %>
                   <% end %>
                  <% end %>
                 <% if array.sum == 0 %>
                 <% else %>
                  <div class="unread-room-num"><%= array.sum %></div>
                 <% end %>

              <% else %>
              <p class="font3">メッセージがありません</p>
             <% end %>
            </div>
           </div>
          <% end %>
         </div>
        </div>
       </div>
      <div class="fixed-bottom">
       <div class="copyright">
        <p>&copy; 2019 foosal</p>
       </div>
      </div>
     </body>
    </html>

app/views/rooms/show.html.erb
    <!-- render :show, layout: falseでapplication.html.erbは反映していない -->
  <!DOCTYPE html>
   <html lang="ja">
    <head>
     <meta charset="utf-8">
      <title>Footsal</title>
       <%= csrf_meta_tags %>
       <%= csp_meta_tag %>
       <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
       <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
       <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
     </head>
      <body>
        <!-- gem auto_session_timeout -->
        <% if user_signed_in? %>
        <div class="user_logged"></div>
        <%= auto_session_timeout_js %>
      <% end %>
        <div class="room-header-block"></div>
       <nav class="navbar navbar-expand bg-light fixed-top">
        <a href="/rooms/"><i class="fas fa-chevron-left fa-2x navbar-brand"></i></a>
         <div class="collapse navbar-collapse justify-content-center">
          <div class="navbar-nav">
           <a class="nav-item nav-link font2" href="/users/<%= @otherentry.user.id %>"><%= @otherentry.user.captain_name %></a>
          </div>
         </div>
        </nav>
         <div class="room-backcolor">
          <div class="frame">
           <% if @message.present? %>
            <% @messages.each do |m| %>
             <% if m.user == current_user %>
              <div class="talk-light message-height">
               <div class="room-contain-me">
                <div class="talk-and-time-me">
                 <div class="room-talk-me"><%= simple_format(m.content) %></div>
                  <div class="room-time"><%= m.created_at.strftime("%Y-%m-%d %H:%M") %></div>
                 </div>
                </div>
               </div>
              <% else %>
               <div class="room-contain-you message-height">
                <div class="image-icon">
                 <%= attachment_image_tag m.user, :image, :fill, 63, 63, fallback: "no_image2.png", class: 'radius' %>
                </div>
                 <div class="talk-and-time-you">
                  <div class="room-talk-you"><%= simple_format(m.content) %></div>
                   <div class="room-time"><%= m.created_at.strftime("%Y-%m-%d %H:%M") %></div>
                  </div>
                 </div>
                <% end %>
               <% end %>
              <% else %>
              <h3 class="center"><p>メッセージはまだありません</p></h3>
             <% end %>
              <%= form_for @message, :url => { :controller => :messages, :action => :create } do |f| %>
               <div class="input-button">
                 <%= f.text_area :content, placeholder: 'メッセージを入力してください', row: 5, class: 'talk-input' %>
                 <%= f.hidden_field :read_flg, value: 1 %>
                 <%= f.hidden_field :room_id, value: @room.id %>
                 <%= f.submit '送信', class: 'send-button' %>
                </div>
                 <div class="fixed-block"></div>
               <% end %>
               </div>
              </div>
             </body>
            </html>
          <script type="text/javascript">
            $(document).ready(function(){
              var height = 56;
              // 各メッセージのheightを取得して足していく
              $(".message-height").each( function() {
                height += ($(this).height());
              });
              // room内画面に繊維した時合計したheight位置から始まる
              $(window).scrollTop(height);
              // room内で再読み込みすると合計height位置に戻る
              $(window).on('beforeunload', function() {
                $(window).scrollTop(height);
              });
            });
          </script>