config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  post 'contacts/create'
  get 'teamdetails/new'
  post 'teamdetails' => 'teamdetails#create'
  resources :posts
  root 'home#home'
  get 'home' => 'home#home'
  get 'home/terms' => 'home#terms'
  get 'home/privacy' => 'home#privacy'
  get 'home/caution' => 'home#caution'
  get 'home/timeout' => 'home#timeout'

  get 'admins' => 'admins#index'
  get 'admins/seek' => 'admins#seek'
  get 'admins/people' => 'admins#people'
  get 'admins/users/:id/person' => 'admins#person', as: 'person'
  get 'admins/users/:id/person_edit' => 'admins#person_edit', as: 'person_edit'
  patch 'admins/users/:id' => 'admins#update'
  put 'admins/users/:id' => 'admins#update'
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
 }
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
 }

  get 'application/session_time'
  devise_scope :user do
    match 'active' => 'users/sessions#active', via: :get
    match 'timeout' => 'users/sessions#timeout', via: :get
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :users, except: [:create] do
   collection do
    get 'search'
   end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: {maximum: 50}
  validates :body, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate!, only: [:new, :show, :edit, :update]
  before_action :new_message_badge, if: :user_signed_in?

  def index
     @teamdetails = TeamDetail.all
     @posts = Post.all.reverse_order
     @plan = Post.where(conditions: "予定を合わせて対戦").reverse_order
     @now = Post.where(conditions: "いますぐ試合したい").reverse_order
     @pleasant = Post.where(conditions: "わいわい試合したい").reverse_order
     @serious = Post.where(conditions: "真剣勝負!").reverse_order
     render :index, layout: false
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if admin_signed_in?
      flash[:posterror] = 'ログインユーザーのみ投稿できます'
      render :new
    else
      @post.user_id = current_user.id
    if  @post.save
      redirect_to posts_path
    else
      render action: :new
    end
   end
  end

  def show
    if admin_signed_in?
      @post = Post.find(params[:id])
      @user = @post.user
      @team = TeamDetail.find_by(user_id: @user.id)
    else
    @post = Post.find(params[:id])
    @user = @post.user
    @team = TeamDetail.find_by(user_id: @user.id)
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
     unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
       end
       if @isRoom
       else
         @room = Room.new
         @entry = Entry.new
       end
     end
   end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:destroypostmessage] = '削除しました'
      redirect_to posts_path
    else
      render :show
  end
end

  private
  def post_params
    params.require(:post).permit(:title, :body, :conditions)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_now.html.erb
        <% @now.each do |n| %>
        <div class="posts-frame1">
          <div class="double-frame">
           <div class="change-post-condition body-now"><%= n.conditions %></div>
            <div class="font3 time-right"><%= n.created_at.strftime("%Y-%m-%d %H:%M") %></div>
             <div class="font1 posts-frame2 center margin2 postsblock"><p><%= link_to n.title, post_path(n) %></p></div>
              <div class="postsblock"><p><%= n.body %></p></div>
               <div class="margin-right1"><%= n.user.team_name %></div>
                <% @teamdetails.each do |team| %>
                 <% if n.user_id == team.user_id %>
                  <div class="margin-right1"><span class="font3">活動地域:</span><%= team.active_area %></div>
                  <div class="margin-right1"><span class="font3">活動時間:</span><%= team.active_time %></div>
                 <% if user_signed_in? %>
                   <div class="right-link"><%= link_to '詳細', post_path(n) %></div>
                  <% else %>
                 <% end %>
                </div>
               <% end %>
              <% end %>
             <% end %>
            </div>

         <div class="fixed-bottom  bg-light post-footer">
          <nav class="navbar navbar-expand justify-content-around">
           <ul class="nav navbar-nav">
            <li class="nav-item posts-icon"><a href="/posts/new"><i class="far fa-clipboard"></i>掲示板に投稿する</a></li>
            <li class="nav-item posts-icon"><a href="/posts"><i class="fas fa-reply"></i>投稿一覧に戻る</a></li>
           </ul>
          </nav>
         </div>
          <div class="fixed-block"></div>

app/views/posts/_plan.html.erb
      <% @plan.each do |p| %>
       <div class="posts-frame1">
        <div class="double-frame">
         <div class="change-post-condition body-plan"><%= p.conditions %></div>
          <div class="font3 time-right"><%= p.created_at.strftime("%Y-%m-%d %H:%M") %></div>
           <div class="font1 posts-frame2 center margin2 postsblock"><p><%= link_to p.title, post_path(p) %></p></div>
            <div class="postsblock"><p><%= p.body %></p></div>
             <div class="margin-right1"><%= p.user.team_name %></div>
              <% @teamdetails.each do |team| %>
               <% if p.user_id == team.user_id %>
                <div class="margin-right1"><span class="font3">活動地域:</span><%= team.active_area %></div>
                <div class="margin-right1"><span class="font3">活動時間:</span><%= team.active_time %></div>
               <% if user_signed_in? %>
                <div class="right-link"><%= link_to '詳細', post_path(p) %></div>
               <% else %>
              <% end %>
             </div>
            <% end %>
           <% end %>
          <% end %>
         </div>

       <div class="fixed-bottom  bg-light post-footer">
        <nav class="navbar navbar-expand justify-content-around">
         <ul class="nav navbar-nav">
          <li class="nav-item posts-icon"><a href="/posts/new"><i class="far fa-clipboard"></i>掲示板に投稿する</a></li>
          <li class="nav-item posts-icon"><a href="/posts"><i class="fas fa-reply"></i>投稿一覧に戻る</a></li>
         </ul>
        </nav>
       </div>
        <div class="fixed-block"></div>

app/views/posts/_pleasant.html.erb
    <% @pleasant.each do |p| %>
     <div class="posts-frame1">
      <div class="double-frame">
       <div class="change-post-condition body-pleasant"><%= p.conditions %></div>
        <div class="font3 time-right"><%= p.created_at.strftime("%Y-%m-%d %H:%M") %></div>
         <div class="font1 posts-frame2 center margin2 postsblock"><p><%= link_to p.title, post_path(p) %></p></div>
          <div class="postsblock"><p><%= p.body %></p></div>
           <div class="margin-right1"><%= p.user.team_name %></div>
            <% @teamdetails.each do |team| %>
             <% if p.user_id == team.user_id %>
              <div class="margin-right1"><span class="font3">活動地域:</span><%= team.active_area %></div>
              <div class="margin-right1"><span class="font3">活動時間:</span><%= team.active_time %></div>
             <% if user_signed_in? %>
               <div class="right-link"><%= link_to '詳細', post_path(p) %></div>
              <% else %>
             <% end %>
            </div>
           <% end %>
          <% end %>
         <% end %>
        </div>

      <div class="fixed-bottom  bg-light post-footer">
       <nav class="navbar navbar-expand justify-content-around">
        <ul class="nav navbar-nav">
         <li class="nav-item posts-icon"><a href="/posts/new"><i class="far fa-clipboard"></i>掲示板に投稿する</a></li>
         <li class="nav-item posts-icon"><a href="/posts"><i class="fas fa-reply"></i>投稿一覧に戻る</a></li>
        </ul>
       </nav>
      </div>
       <div class="fixed-block"></div>

app/views/posts/_serious.html.erb
     <% @serious.each do |s| %>
      <div class="posts-frame1">
       <div class="double-frame">
        <div class="change-post-condition body-serious"><%= s.conditions %></div>
         <div class="font3 time-right"><%= s.created_at.strftime("%Y-%m-%d %H:%M") %></div>
          <div class="font1 posts-frame2 center margin2 postsblock"><p><%= link_to s.title, post_path(s) %></p></div>
           <div class="postsblock"><p><%= s.body %></p></div>
            <div class="margin-right1"><%= s.user.team_name %></div>
             <% @teamdetails.each do |team| %>
              <% if s.user_id == team.user_id %>
               <div class="margin-right1"><span class="font3">活動地域:</span><%= team.active_area %></div>
               <div class="margin-right1"><span class="font3">活動時間:</span><%= team.active_time %></div>
              <% if user_signed_in? %>
                <div class="right-link"><%= link_to '詳細', post_path(s) %></div>
               <% else %>
              <% end %>
             </div>
            <% end %>
           <% end %>
          <% end %>
         </div>

       <div class="fixed-bottom  bg-light post-footer">
        <nav class="navbar navbar-expand justify-content-around">
         <ul class="nav navbar-nav">
          <li class="nav-item posts-icon"><a href="/posts/new"><i class="far fa-clipboard"></i>掲示板に投稿する</a></li>
          <li class="nav-item posts-icon"><a href="/posts"><i class="fas fa-reply"></i>投稿一覧に戻る</a></li>
         </ul>
        </nav>
       </div>
        <div class="fixed-block"></div>

app/views/posts/index.html.erb
 <!DOCTYPE html>
  <html lang="ja">
   <head>
    <title>Footsal</title>
     <%= csrf_meta_tags %>
     <%= csp_meta_tag %>
     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
   <body>
     <!-- gem auto_session_timeout -->
     <% if user_signed_in? %>
     <div class="user_logged"></div>
     <%= auto_session_timeout_js %>
   <% end %>
    <header>
     <!-- navbar-expand-○でグローバルメニュー表示（なければハンバーガメニュー） -->
      <nav class="navbar navbar-expand-lg navbar-expand-md navbar-dark bg-primary">
      <a href="/home" id="logo" class="navbar-brand"><img src="/images/footsal15.png" alt="foosal"></a>
        <!-- <button>~</button>でハンバーガメニュー作成。data-targetで指定したIDやクラスがハンバーガメニューとなる -->
         <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
       <div class="collapse navbar-collapse" id="navbarNav">
        <% if user_signed_in? %>
         <ul class="nav navbar-nav ml-auto">
          <li class="nav-item active"><%= link_to "ホーム", root_path, class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "マイページ", user_path(current_user), class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "チーム一覧", users_path, class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "トークルーム", rooms_path, class: "nav-link" %>
            <% if @unreads == 0 %>
           <% else %>
           <!--Applicationhelper.rbに記載 -->
            <%= new_message_badge %>
           <% end %>
          </li>
          <li class="nav-item active"><%= link_to "掲示板", posts_path, class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
         </ul>
        <% elsif admin_signed_in? %>
         <ul class="nav navbar-nav ml-auto">
          <li class="nav-item"><%= link_to "管理ホーム", admins_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ユーザー情報", admins_people_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "掲示板へ", posts_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %></li>
         </ul>
        <% else %>
         <ul class="nav navbar-nav ml-auto">
          <li class="nav-item"><%= link_to "ホーム", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "会員登録",new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ログイン", user_session_path, class: "nav-link" %></li>
         </ul>
        <% end %>
       </div>
      </nav>
     </header>
    <div class="center margin1">
     <% if flash[:destroypostmessage] %>
      <p><%= flash[:destroypostmessage] %></p>
     <% end %>
    </div>
   <h1 class="center margin1">掲示板投稿一覧</h1>
    <div class="container">
     <div class="row justify-content-center">
      <div class="col-md-8 footer-margin-bottom">
       <div class="center" id="plan"><p>予定を合わせて対戦</p></div>
       <div class="center" id="now"><p>いますぐ試合したい</p></div>
       <div class="center" id="pleasant"><p>わいわい試合したい</p></div>
       <div class="center" id="serious"><p>真剣勝負!</p></div>
        <div class="change-post">
        <% @posts.each do |post| %>
        <div class="posts-frame1">
          <div class="double-frame">
            <% if post.conditions == '予定を合わせて対戦' %>
            <div class="change-post-condition body-plan"><%= post.conditions %></div>
            <% elsif post.conditions == 'いますぐ試合したい' %>
            <div class="change-post-condition body-now"><%= post.conditions %></div>
            <% elsif post.conditions == 'わいわい試合したい' %>
            <div class="change-post-condition body-pleasant"><%= post.conditions %></div>
            <% elsif post.conditions == '真剣勝負!' %>
            <div class="change-post-condition body-serious"><%= post.conditions %></div>
            <% else %>
            <div style="float: left;"><%= post.conditions %></div>
            <% end %>
            <div class="font3 time-right"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></div>
          <div class="font1 posts-frame2 center margin2 postsblock"><p><%= link_to post.title, post_path(post) %></p></div>
            <div class="postsblock"><p><%= post.body %></p></div>
             <div class="margin-right1"><%= post.user.team_name %></div>
              <% @teamdetails.each do |team| %>
               <% if post.user_id == team.user_id %>
                  <div class="margin-right1"><span class="font3">活動地域:</span><%= team.active_area %></div>
                  <div class="margin-right1"><span class="font3">活動時間:</span><%= team.active_time %></div>
                   <% if user_signed_in? %>
                  <div class="right-link"><%= link_to '詳細', post_path(post) %></div>
                  <% else %>
                 <% end %>
                </div>
               <% end %>
              <% end %>
             <% end %>
            </div>
          </div>
         </div>
        </div>
       </div>
       <div class="fixed-bottom  bg-light post-footer">
        <nav class="navbar navbar-expand justify-content-around px-0">
         <ul class="nav navbar-nav">
          <li class="nav-item  mx-0 posts-icon"><a href="/posts/new"><i class="far fa-clipboard"></i>掲示板に投稿する</a></li>
          <li class="nav-item mx-0 posts-icon"><a href="/posts"><i class="fas fa-reply"></i>投稿一覧に戻る</a></li>
         </ul>
        </nav>
       </div>
         <!-- クリックで条件検索 -->
         <script>
          $("#plan").on('click', function() {
           $('.change-post').html('<%= j(render partial: "posts/plan", locals: {plan: @plan}) %>');
            });
           $("#now").on('click', function() {
            $('.change-post').html('<%= j(render partial: "posts/now", locals: {now: @now}) %>');
             });
            $("#pleasant").on('click', function() {
             $('.change-post').html('<%= j(render partial: "posts/pleasant", locals: {pleasant: @pleasant}) %>');
              });
             $("#serious").on('click', function() {
              $('.change-post').html('<%= j(render partial: "posts/serious", locals: {serious: @serious}) %>');
               });
             </script>

app/views/posts/new.html.erb
   <div class="center">
    <% if flash[:posterror] %>
     <p><%= flash[:posterror] %></p>
    </div>
   <% end %>
    <h1 class="center margin1">掲示板投稿</h1>
     <div class="container">
      <div class="row justify-content-center">
       <div class="col-md-8">
        <%= form_for(@post) do |f| %>
         <%= render 'layouts/error_messages', model: f.object %>
          <h4 class="font4">タイトル</h4>
           <div class="form-group">
            <%= f.text_field :title, placeholder: 'タイトル', class: 'form-control' %>
           </div>
          <h4 class="font4">本文</h4>
           <div class="form-group">
            <%= f.text_area :body, row: 5, placeholder: '入力してください', class: 'form-control' %>
           </div>
          <h4 class="font4">条件</h4>
           <div class="form-group various-select">
            <%= f.select :conditions, [["予定を合わせて対戦", "予定を合わせて対戦"], ["いますぐ試合したい", "いますぐ試合したい"], ["わいわい試合したい", "わいわい試合したい"], ["真剣勝負!", "真剣勝負!"]] %>
           </div>
           <%= f.submit '投稿', class: 'btn btn-primary various-width margin2' %>
          <% end %>
         </div>
        </div>
       </div>

app/views/posts/search.html.erb
<h1>検索結果</h1>

app/views/posts/show.html.erb
<a class="posts-icon" href="/posts/"><i class="fas fa-chevron-left fa-2x navbar-brand "></i></a>
<div class="container">
 <div class="row justify-content-center">
  <div class="col-md-8 center">
   <div class="double-frame">
    <div class="posts-frame2"><p><%= @post.title %></p></div>
     <div class="margin2"><p><%= @post.body %></p></div>
    </div>
   </div>
  </div>
 </div>
 <% if admin_signed_in? %>
 <div class="container">
  <div class="row">
   <div class="col-lg-4 col-md-6 col-sm-6 center">
    <div class="margin1 smartphone"><%= attachment_image_tag @post.user, :image, :fill, 300, 300, fallback: "no_image.png" %></div>
    <div class="margin2"><%= link_to "この投稿を削除", post_path(@post), method: :delete, data: { confirm: 'この投稿を削除します、よろしいですか？' }, class: "pull-danger", class: "btn btn-danger btn-xs various-width" %></div>
    </div>
     <div class="col-lg-8 col-md-6 col-sm-6 ">
      <div class="font3">名前</div>
       <div class="font1 show-border"><%= @post.user.name %></div>
      <div class="font3">キャプテン</div>
       <div class="font1 show-border"><%= @post.user.captain_name %></div>
      <div class="font3">チーム名</div>
       <div class="font1 show-border"><%= @post.user.team_name %></div>
        <% if @post.user.team_detail.present? %>
         <div class="font3">男性人数</div>
          <div class="font1 show-border"><%= @team.male %></div>
         <div class="font3">女性人数</div>
          <div class="font1 show-border"><%= @team.female %></div>
         <div class="font3">経験者人数</div>
          <div class="font1 show-border"><%= @team.experience %></div>
         <div class="font3">初心者人数</div>
          <div class="font1 show-border"><%= @team.beginner %></div>
         <div class="font3">紹介文</div>
          <div class="font1 show-border"><%= @team.introduction %></div>
         <div class="font3">チームレベル</div>
          <div class="font1 show-border"><%= @team.team_level %></div>
         <div class="font3">活動地域</div>
          <div class="font1 show-border"><%= @team.active_area %></div>
         <div class="font3">活動時間</div>
          <div class="font1 show-border"><%= @team.active_time %></div>
         <% end %>
        </div>
       </div>
      </div>
  <% elsif @post.user_id == current_user.id %>
   <div class="container">
    <div class="row">
     <div class="col-lg-4 col-md-6 col-sm-6 center">
      <div class="margin1 smartphone"><%= attachment_image_tag @post.user, :image, :fill, 300, 300, fallback: "no_image.png" %></div>
       <div class="margin2"><%= link_to '編集する', edit_user_path(current_user.id), class: 'btn btn-success button-width' %></div>
       <div class="margin2"><%= link_to 'pass変更', edit_user_registration_path, class: 'btn btn-primary button-width' %></div>
      </div>
       <div class="col-lg-8 col-md-6 col-sm-6 ">
        <div class="font3">名前</div>
         <div class="font1 show-border"><%= @post.user.name %></div>
        <div class="font3">キャプテン</div>
         <div class="font1 show-border"><%= @post.user.captain_name %></div>
        <div class="font3">チーム名</div>
         <div class="font1 show-border"><%= @post.user.team_name %></div>
          <% if @post.user.team_detail.present? %>
           <div class="font3">男性人数</div>
            <div class="font1 show-border"><%= @team.male %></div>
           <div class="font3">女性人数</div>
            <div class="font1 show-border"><%= @team.female %></div>
           <div class="font3">経験者人数</div>
            <div class="font1 show-border"><%= @team.experience %></div>
           <div class="font3">初心者人数</div>
            <div class="font1 show-border"><%= @team.beginner %></div>
           <div class="font3">紹介文</div>
            <div class="font1 show-border"><%= @team.introduction %></div>
           <div class="font3">チームレベル</div>
            <div class="font1 show-border"><%= @team.team_level %></div>
           <div class="font3">活動地域</div>
            <div class="font1 show-border"><%= @team.active_area %></div>
           <div class="font3">活動時間</div>
            <div class="font1 show-border"><%= @team.active_time %></div>
           <% end %>
          </div>
         </div>
        </div>
       <% else %>
       <h1 class="center margin1">ユーザー情報</h1>
        <div class="container">
         <div class="row">
          <div class="col-lg-4 col-md-6 col-sm-6 center">
           <div class="margin1 smartphone"><%= attachment_image_tag @post.user, :image, :fill, 300, 300, fallback: "no_image.png" %></div>
            <% if @isRoom == true %>
             <!--すでにroomがあるならそのroomへ、そうでなければroomを新たにcreate-->
             <div class="margin2 font1"><p><a href="/rooms/<%= @roomId %>">トークルームへ</a></p></div>
            <% else %>
             <%= form_for(@room) do |f| %>
              <%= fields_for @entry do |e| %>
               <% e.hidden_field :user_id, value: @post.user_id %>
              <% end %>
              <div class="margin2"><%= f.submit "トークを始める", class: 'btn btn-info' %></div>
             <% end %>
            <% end %>
           </div>
            <div class="col-lg-8 col-md-6 col-sm-6 ">
             <div class="font3">キャプテン</div>
              <div class="font1 show-border"><%= @post.user.captain_name %></div>
             <div class="font3">チーム名</div>
              <div class="font1 show-border"><%= @post.user.team_name %></div>
               <% if @user.team_detail.present? %>
                <div class="font3">男性人数</div>
                 <div class="font1 show-border"><%= @team.male %></div>
                <div class="font3">女性人数</div>
                 <div class="font1 show-border"><%= @team.female %></div>
                <div class="font3">経験者人数</div>
                 <div class="font1 show-border"><%= @team.experience %></div>
                <div class="font3">初心者人数</div>
                 <div class="font1 show-border"><%= @team.beginner %></div>
                <div class="font3">紹介文</div>
                 <div class="font1 show-border"><%= @team.introduction %></div>
                <div class="font3">チームレベル</div>
                 <div class="font1 show-border"><%= @team.team_level %></div>
                <div class="font3">活動地域</div>
                 <div class="font1 show-border"><%= @team.active_area %></div>
                <div class="font3">活動時間</div>
                 <div class="font1 show-border"><%= @team.active_time %></div>
                <% end %>
               </div>
              </div>
             </div>
            <% end %>